languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]
publishDir = 'docs'

baseURL = "https://memv.ennbee.uk/whoami/"
title = "Nick Benton"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#293341"
colorPageBackground = "#bbc5d3"
colorPrimary = "#286cf0"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#42b8fa"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#272c2f"
colorRightColumnBodyText = "#272c2f"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#42b8fa"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = false
